# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BldgBase',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('addr', models.TextField(null=True)),
                ('lati', models.FloatField(null=True)),
                ('longi', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'Bldg_Base',
            },
        ),
        migrations.CreateModel(
            name='RestrBase',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('floor', models.IntegerField(null=True)),
                ('addr', models.TextField(null=True)),
                ('lati', models.FloatField(null=True)),
                ('longi', models.FloatField(null=True)),
                ('distHQ', models.FloatField(null=True)),
                ('distIT', models.FloatField(null=True)),
                ('uptTime', models.DateTimeField()),
                ('avgRating', models.FloatField(default=-1)),
                ('hitScore', models.IntegerField(default=0)),
                ('dcodeURL', models.URLField(null=True)),
                ('thumbnailURL', models.URLField(null=True)),
                ('tag', models.TextField(null=True)),
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='func.BldgBase')),
            ],
            options={
                'db_table': 'Restr_Base',
            },
        ),
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nickName', models.CharField(max_length=30)),
                ('regTime', models.DateTimeField()),
                ('lastConnTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'User_Base',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewTime', models.DateTimeField()),
                ('rating', models.FloatField()),
                ('reviewText', models.TextField(null=True)),
                ('rid', models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.CASCADE, to='func.RestrBase')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='func.UserBase')),
            ],
            options={
                'db_table': 'User_Review',
            },
        ),
        migrations.CreateModel(
            name='UserViewHist',
            fields=[
                ('hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('viewTime', models.DateTimeField()),
                ('staySeconds', models.IntegerField(null=True)),
                ('rid', models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.CASCADE, to='func.RestrBase')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='func.UserBase')),
            ],
            options={
                'db_table': 'User_View_Hist',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userviewhist',
            unique_together=set([('sid', 'rid', 'viewTime')]),
        ),
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together=set([('sid', 'rid', 'reviewTime')]),
        ),
    ]
