# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicknameSrcAdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(max_length=30)),
                ('cnt_used', models.IntegerField(default=0)),
                ('last_used_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Nickname_Src_Adj',
            },
        ),
        migrations.CreateModel(
            name='NicknameSrcNoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(max_length=30)),
                ('cnt_used', models.IntegerField(default=0)),
                ('last_used_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Nickname_Src_Noun',
            },
        ),
        migrations.CreateModel(
            name='RestrCrawl',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('addr', models.TextField(null=True)),
                ('lati', models.FloatField(null=True)),
                ('longi', models.FloatField(null=True)),
                ('distHQ', models.FloatField(null=True)),
                ('distIT', models.FloatField(null=True)),
                ('uptTime', models.DateTimeField()),
                ('referenceURL', models.URLField()),
                ('thumbnailURL', models.URLField(null=True)),
            ],
            options={
                'db_table': 'Restr_Crawl',
            },
        ),
        migrations.RenameField(
            model_name='restrbase',
            old_name='dcodeURL',
            new_name='referenceURL',
        ),
        migrations.AddField(
            model_name='restrcrawl',
            name='rid',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.CASCADE, to='func.RestrBase'),
        ),
    ]
